### ISSUE TITLE
途中にロビーを挟むと、その部分を飛ばせない

### ISSUE THREAD

**Issue by mitsu-ksgr** [nozzzzzzz/analyze-splatoon2#2]
リザルト画面のあとに「つづける」を選ばず「やめる」を押して（あるいは放置したりして）ロビーに戻りその後またガチマに入る、というパターンだと、その部分を識別できないみたいです。
これができると非常に助かりがあるのですが、どうでしょう :thinking:

**Comment by nozz-des** [comment]
識別できないっていうのは、試合以外を試合として認識してしまうってことでしょうか？
今の所、試合orNOTは尺の長さでしか判断していないので、ブラックアウト後の数フレームを見て判定かけるとかで実装してみます😎

**Comment by nozz-des** [comment]
多分できました。また問題あればissueください！ありがとうございました！
